### ISSUE TITLE
Suggestion: Config option to hide sidepanel

### ISSUE THREAD

**Issue by YvesW** [Zabith4/Salve-Amulet-Checker#3]
Currently it clutters up the sidepanel, while an ingame notification/infobox is good enough. There is sadly no way in the config to turn off the sidepanel. Would love if you could add that option!

**Comment by ZeroGraviga** [comment]
> 

Thanks for the suggestion,  I'll look into adding that feature!

**Comment by NickSpaghetti** [comment]
Thanks for the suggestion, I'll look into adding that option in the configuration!
